name: Test ref-exchange 
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_ref_exchange:
    runs-on: ubuntu-latest 
    container:
      image: nearprotocol/contract-builder:latest
      env:
        RUSTFLAGS: -C link-arg=-s
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ref-exchange && \
          rustup toolchain install stable-2021-11-01 && \
          rustup default stable-2021-11-01 && \
          ./build_local.sh && \
          cargo test -- --skip fuzzy
